package org.sopt.hashi.media.internal.queue;

public enum MediaTransformFailureCode {

    ANIMATED_IMAGE_NOT_SUPPORTED,
    IMAGE_DIMENSION_LIMIT_EXCEEDED,
    IMAGE_PIXEL_LIMIT_EXCEEDED,
    INVALID_IMAGE_DATA,
    SOURCE_FILE_TOO_LARGE,
    SOURCE_MIME_MISMATCH,
    SOURCE_SIZE_MISMATCH,
    UNSUPPORTED_IMAGE_TYPE
}
